# Индексация и выборки:
1. Как получить 1 элемент.
2. Как получить срез элементов (slice).
3. Выбор элементов в режиме broadcast.
4. Индексация и выборки в случае 2-х измерений. 
5. Условная выборка (conditional selection).

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[5]

np.int64(5)

In [4]:
arr[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [5]:
# функция broadcast, присваивание значении (не работает на обычных списках). 
arr[:10] = 100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10])

In [6]:
arr = np.arange(0,11)

In [7]:
srez_arr = arr[0:5]
srez_arr

array([0, 1, 2, 3, 4])

In [10]:
# присвоим срезу другие значения
srez_arr[:] = 99
srez_arr

array([99, 99, 99, 99, 99])

In [11]:
# в итоге исходный массив изменен, т.к. это была ссылка
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [13]:
# если хотим сделать копию элементов.
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:] = 100 
print(arr)
print(arr_copy)

[99 99 99 99 99  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]


In [20]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d.shape

(3, 3)

In [22]:
# Получаем 1-ую строку матрицы
arr_2d[0]

array([ 5, 10, 15])

In [24]:
arr_2d[2]

array([35, 40, 45])

In [28]:
# Возьмем элемент из массива
print(arr_2d[1][1])
print(arr_2d[1,1]) # либо так 

25
25


In [29]:
print(arr_2d[0,2])

15


In [37]:
# срез 
print(arr_2d[0:2,1:])

[[10 15]
 [25 30]]


## Условная выборка (conditional selection)

In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
bool_arr = arr > 4 
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
# т.е. задали условие выборки переменной bool_arr.
print(arr[bool_arr])
print(arr[arr>4]) # либо так. 

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]
