In [1]:
import numpy as np

In [3]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# прибавляем число отдельно к каждому элементу массива
arr_5 = arr + 5
print(arr_5)

[ 5  6  7  8  9 10 11 12 13 14]


In [8]:
arr_5 + arr 

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [10]:
# numpy и деление на ноль 
arr / arr

/var/folders/2q/k8j7_x7j65q07cgb4j_r745h0000gn/T/ipykernel_3001/1383993873.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / arr

/var/folders/2q/k8j7_x7j65q07cgb4j_r745h0000gn/T/ipykernel_3001/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
# корень всех значении
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
# log
np.log(arr)

/var/folders/2q/k8j7_x7j65q07cgb4j_r745h0000gn/T/ipykernel_3001/3930319491.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [14]:
# сумма всех элементов массива 
arr.sum()

np.int64(45)

In [15]:
arr.mean()

np.float64(4.5)

In [16]:
arr.max()

np.int64(9)

In [17]:
arr.var()

np.float64(8.25)

In [18]:
arr.std()

np.float64(2.8722813232690143)

In [23]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
print(arr_2d.sum(1)) # сумма по строкам
print(arr_2d.sum(0)) # сумма по колонкам

[ 10  35  60  85 110]
[50 55 60 65 70]
