In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
myarr = np.array(mylist)

In [7]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# матрица из нулей 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# матрица из единиц
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# равноотстоящие числа в массиве
np.linspace(1,5,3)

array([1., 3., 5.])

In [15]:
# матрица на главной диагонали 1, на остальных нули.
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# uniform distribution
np.random.rand(1)

array([0.88248464])

In [29]:
np.random.rand(5,3)

array([[0.95030981, 0.31395515, 0.52958714],
       [0.51792204, 0.95547212, 0.11458826],
       [0.052308  , 0.78261146, 0.87119114],
       [0.73441414, 0.66643443, 0.15937392],
       [0.401994  , 0.7267217 , 0.10920848]])

In [32]:
# normal distribution
np.random.randn(5)

array([ 0.4630116 , -0.03075648, -0.97654985, -0.07550095, -0.42842132])

In [33]:
np.random.randn(5,3)

array([[-0.61912627,  0.92990276, -1.62302012],
       [ 0.70790788, -0.79659975, -0.55502526],
       [ 1.57735857,  0.18544206, -0.3021619 ],
       [-0.84257749,  1.12702358, -1.12656061],
       [ 0.77419281,  2.37260449,  1.40230016]])

In [34]:
# uniform
np.random.randint(0,101,10)

array([ 7, 64, 89,  6, 18, 64, 66,  5, 88, 72])

In [36]:
# или кортеж 
np.random.randint(0,101,(4,5))

array([[35, 70, 74, 18, 91],
       [44, 82, 12, 88, 75],
       [ 5, 88,  4, 44, 56],
       [92, 68, 97, 39, 89]])

In [41]:
# должны запускаться в одной ячейке
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [65]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
# позволяет изменять размерность массива
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr = np.random.randint(0,101,10)
ranarr 

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [48]:
ranarr.max()

np.int64(99)

In [49]:
ranarr.min()

np.int64(2)

In [50]:
# индекс максимального числа
ranarr.argmax()

np.int64(5)

In [51]:
ranarr.argmin()

np.int64(7)

In [58]:
# тип данных (не функция)
ranarr.dtype

dtype('int64')

In [67]:
# можно посмотреть размер или форму массива. (не функция, а атрибут)
arr.shape

(25,)

In [68]:
arr = arr.reshape(5,5)

In [70]:
arr.shape

(5, 5)

In [72]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [73]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])