In [1]:
import numpy as np

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
np.random.randn(25)

array([ 0.10856968,  0.36709846, -0.84229433,  1.75486116, -1.45505133,
        1.65511389, -0.17661947,  0.7795516 , -0.77507025,  1.33386689,
        1.71433756, -0.65381963, -1.85722785,  0.37899513, -0.3056263 ,
       -1.20010431, -0.7917455 , -0.35635905,  1.22439099, -0.15515456,
        0.86200167,  0.56042424,  0.53807464, -0.20000107,  1.66855726])

In [10]:
np.linspace(0.01, 1, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [11]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
mat[2:,1:3]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [20]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [26]:
import pandas as pd
# Диаметр в км, Объём в 10^9 км³, Масса в 10^21 кг
planets_list = [['Меркурий', 4879,  60.83,  330.2], ['Марс',     6779,  163.18,  641.85],     
                ['Венера',  12104, 928.43, 4868.5], ['Земля',   12742, 1083.21,  5973.6], 
                ['Нептун',  49244,  62540, 102430], ['Уран',    50724,   68340,   86832],
                ['Сатурн', 116460, 827130, 568460], ['Юпитер', 139820, 1431280, 1898600] ]
planets = pd.DataFrame(planets_list, columns=['Название','Диаметр', 'Объём', 'Масса'])

# Напишите Ваше решение здесь
planets

Название  Диаметр       Объём       Масса
0  Меркурий     4879       60.83      330.20
1      Марс     6779      163.18      641.85
2    Венера    12104      928.43     4868.50
3     Земля    12742     1083.21     5973.60
4    Нептун    49244    62540.00   102430.00
5      Уран    50724    68340.00    86832.00
6    Сатурн   116460   827130.00   568460.00
7    Юпитер   139820  1431280.00  1898600.00

In [32]:
planets.iloc[3]['Диаметр']

np.int64(12742)